// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqbiN8e8f396Yd1vvjTZNSp9McxJece8',
    appId: '1:440722473262:web:d8edcd81dfd825d5903abf',
    messagingSenderId: '440722473262',
    projectId: 'pak-cakeshop',
    authDomain: 'pak-cakeshop.firebaseapp.com',
    storageBucket: 'pak-cakeshop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHSBOPKK_a3fp2O8BshxEpfAoh1PJD9E',
    appId: '1:440722473262:android:1331bfac481ac8c3903abf',
    messagingSenderId: '440722473262',
    projectId: 'pak-cakeshop',
    storageBucket: 'pak-cakeshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmDDHtQublJpowmLbsE3-5cb1hudbrqg',
    appId: '1:440722473262:ios:17cd799ed437cfb6903abf',
    messagingSenderId: '440722473262',
    projectId: 'pak-cakeshop',
    storageBucket: 'pak-cakeshop.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );
}
